export { authService } from './auth.service'
export { proprieteService } from './propriete.service'
export { destinationService } from './destination.service'
export { hotelService } from './hotel.service'
export { typeHotelService } from './typeHotel.service'
export type { TypeHotelWithImage } from './typeHotel.service'
export { reservationService } from './reservation.service'
export { favoriService } from './favori.service'
export { avisService } from './avis.service'
export { profileService } from './profile.service'
export { decouverteService } from './decouverte.service'
export { offreService } from './offre.service'
export type { Offre, OffreDetail, PaginatedOffres } from './offre.service'
